[package]
name = "klint"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[package.metadata.rust-analyzer]
# This crate uses #![feature(rustc_private)]
rustc_private = true
